[env]
SHELLCODE_SRC_PATH = "${CARGO_MAKE_WORKING_DIRECTORY}/shellcode/"

[tasks.clean]
script = [
    "cargo clean"
]

[tasks.build-rdi]
script = [
    "cd %SHELLCODE_SRC_PATH%",
    "cargo build --release"
]

[tasks.build-shellcode]
script = [
    "cargo run"
]

[tasks.build]
dependencies = ["build-rdi", "build-shellcode"]
